"""Academic topics extracted from university course catalogs.
Total: 518 topics across 50 disciplines.
Generated: 2026-03-24
"""

ACADEMIC_TOPICS = [
    "5G wireless communication and MIMO systems",
    "A/B testing and multiple hypothesis correction",
    "AI governance and regulatory frameworks",
    "ARIMA models and forecasting",
    "Afrobeat, highlife, and music of the African diaspora",
    "Analyze how social media algorithms shape public discourse and political opinion formation. What are the implications for democratic deliberation?",
    "Analyze how the invention of photography in the 19th century transformed both the practice and purpose of painting. How did artists respond to this technological challenge?",
    "Analyze the aerodynamic challenges of supersonic and hypersonic flight. What materials and design approaches are needed for sustained high-speed flight?",
    "Analyze the causes and consequences of income inequality in the United States over the past five decades. What policy interventions are most supported by economic evidence?",
    "Analyze the causes and consequences of mass incarceration in the United States from a sociological perspective. What reforms show the most promise for reducing recidivism?",
    "Analyze the causes of the fall of the Roman Empire. To what extent were internal factors (political instability, economic decline) more significant than external pressures (barbarian invasions)?",
    "Analyze the challenges of designing biocompatible materials for implantable medical devices. How do material properties affect long-term device performance?",
    "Analyze the challenges of digital preservation. What strategies and standards are most effective for ensuring long-term access to born-digital materials?",
    "Analyze the challenges of managing organizational change in a large corporation. Use a specific case study to illustrate effective and ineffective change management strategies.",
    "Analyze the challenges of predicting earthquakes. What seismological methods show the most promise, and why has reliable prediction remained elusive?",
    "Analyze the child welfare system in the United States, focusing on the disproportionate representation of children of color. What systemic changes are needed to address these disparities?",
    "Analyze the concept of environmental justice. How do race and socioeconomic status correlate with exposure to environmental hazards in the United States?",
    "Analyze the concept of intersectionality as developed by Kimberlé Crenshaw and subsequent scholars. How does it enhance our understanding of systemic inequality?",
    "Analyze the cultural significance of a non-Western dance tradition. How does it reflect and reinforce the values and beliefs of its community of origin?",
    "Analyze the debate between Keynesian and monetarist approaches to managing economic recessions. Which framework better explains the 2008 financial crisis and its aftermath?",
    "Analyze the effectiveness of standardized testing as a measure of educational quality. What are the arguments for and against high-stakes testing, and what alternatives have been proposed?",
    "Analyze the effectiveness of the United Nations Sustainable Development Goals as a framework for international development. What are their strengths and limitations?",
    "Analyze the ethical implications of algorithmic decision-making in criminal justice, lending, and hiring. How can statistical fairness be defined and enforced?",
    "Analyze the ethical implications of large language models. Consider issues of bias, misinformation, intellectual property, and the impact on employment.",
    "Analyze the ethical implications of targeted advertising using personal data. How should companies balance effective marketing with consumer privacy concerns?",
    "Analyze the evidence for and against the embodied cognition hypothesis. How does it challenge traditional computational theories of mind?",
    "Analyze the evidence for the Out of Africa hypothesis of modern human origins. What alternative models have been proposed, and how does the genetic evidence weigh in?",
    "Analyze the evolution of wireless communication from 1G to 5G. What are the key technical innovations that enabled each generation?",
    "Analyze the existentialist conception of freedom and authenticity in Sartre's philosophy. How does his view of radical freedom address the problem of moral responsibility?",
    "Analyze the factors that contribute to democratic backsliding in established democracies. Use at least two case studies to support your argument.",
    "Analyze the growing nursing shortage in the United States. What are the causes, consequences, and most promising policy solutions?",
    "Analyze the hard problem of consciousness as formulated by David Chalmers. Can physicalism adequately explain subjective experience, or is an alternative framework needed?",
    "Analyze the impact of misinformation and disinformation on democratic processes. What role should journalists, platforms, and governments play in combating false information?",
    "Analyze the impact of social media use on adolescent mental health. What does the current research evidence suggest, and what methodological challenges exist?",
    "Analyze the intellectual contributions of the Harlem Renaissance to American culture and politics. How did it reshape the representation of Black identity?",
    "Analyze the legal and ethical issues surrounding data privacy in the digital age. Compare the approaches of the EU (GDPR) and the United States.",
    "Analyze the linguistic features that distinguish creole languages from their lexifier languages. What do creoles reveal about the human capacity for language?",
    "Analyze the mechanisms by which bacteria develop antibiotic resistance. What strategies can be employed to combat the growing threat of multidrug-resistant organisms?",
    "Analyze the policy challenges of regulating artificial intelligence. How should governments balance innovation promotion with risk mitigation?",
    "Analyze the principles of process intensification and how they can be applied to reduce the environmental footprint of chemical manufacturing.",
    "Analyze the relationship between architecture and social behavior. How does the design of public spaces influence community interaction and social cohesion?",
    "Analyze the relationship between microstructure and mechanical properties in engineering alloys. How can processing techniques be used to optimize material performance?",
    "Analyze the relationship between musical form and emotional expression in a specific work from the Classical or Romantic period.",
    "Analyze the relationship between religion and secularism in modern Western democracies. Is secularization theory still a valid framework for understanding contemporary religious trends?",
    "Analyze the relationship between urbanization and environmental degradation in rapidly developing countries. What planning approaches can mitigate negative impacts?",
    "Analyze the representation of heroism in Homer's Iliad and Virgil's Aeneid. How do the different cultural contexts of Greece and Rome shape their conceptions of the hero?",
    "Analyze the role of green chemistry principles in modern industrial chemical processes. Provide specific examples of how waste reduction and atom economy are being implemented.",
    "Analyze the role of landscape and setting in a work of American literature. How does the physical environment function as more than mere backdrop?",
    "Analyze the role of magical realism in the works of Gabriel García Márquez or Isabel Allende. How does this literary mode engage with Latin American history and politics?",
    "Analyze the role of non-governmental organizations in global governance. How do they complement and challenge the authority of states and international organizations?",
    "Analyze the role of probability theory in modern machine learning. How do Bayesian methods differ from frequentist approaches in statistical inference?",
    "Analyze the role of spontaneous symmetry breaking in the Standard Model, particularly in the context of the Higgs mechanism.",
    "Analyze the role of theater in social and political commentary, using specific examples from different historical periods.",
    "Analyze the role of women in the French Revolution. How did their participation challenge and reinforce existing gender norms?",
    "Analyze the significance of the first direct detection of gravitational waves by LIGO for our understanding of general relativity and astrophysics.",
    "Analyze the social determinants of health and their role in creating health disparities. What public health interventions are most effective at addressing these root causes?",
    "Analyze the sociological factors contributing to persistent racial disparities in wealth and income in the United States. How do institutional mechanisms perpetuate inequality?",
    "Analyze the sustainability implications of different transportation infrastructure investments (highways vs. rail vs. cycling infrastructure) in urban planning.",
    "Analyze the tension between free speech and hate speech regulation. How do different legal traditions (US First Amendment vs. European approaches) balance these competing interests?",
    "Analyze the thermodynamic efficiency limits of heat engines. How do modern combined-cycle power plants approach these limits?",
    "Analyze the trade-offs between organic and conventional farming methods in terms of yield, environmental impact, and nutritional quality.",
    "Analyze the use of cinematography and editing in a film of your choice to demonstrate how visual storytelling conveys meaning beyond dialogue.",
    "Analyze the use of unreliable narration in a novel of your choice. How does the narrative technique shape the reader's understanding of the story's themes?",
    "Arabic literary traditions and oral poetry",
    "Athenian democracy and the Peloponnesian War",
    "Athenian pottery and iconography",
    "Bayesian inference and Markov chain Monte Carlo",
    "Beethoven and the development of the symphony",
    "Brechtian epic theater and alienation effect",
    "Buddhist philosophy and mindfulness practices",
    "CRISPR-Cas9 gene editing mechanisms",
    "Cold War proxy wars in Latin America",
    "Compare Bayesian and frequentist approaches to hypothesis testing. In what contexts does each paradigm offer advantages?",
    "Compare Kant's categorical imperative with Mill's utilitarianism as foundations for moral decision-making. Which framework handles moral dilemmas more effectively?",
    "Compare Rawls' theory of justice with Nozick's libertarian framework. Which provides a more compelling foundation for contemporary public policy?",
    "Compare Stanislavski's approach to acting with Brecht's alienation effect. How do these contrasting methods shape the audience's relationship to the performance?",
    "Compare analog and digital signal processing approaches. In what scenarios does each approach offer advantages?",
    "Compare and contrast different approaches to process scheduling in modern operating systems. How do real-time systems differ from general-purpose systems?",
    "Compare and contrast the Copenhagen interpretation and the many-worlds interpretation of quantum mechanics. Which do you find more compelling, and why?",
    "Compare batch and continuous processing in pharmaceutical manufacturing. What factors determine the optimal choice?",
    "Compare carbon tax and cap-and-trade systems as policy tools for reducing greenhouse gas emissions. Which approach is more effective and politically feasible?",
    "Compare cognitive behavioral therapy and psychodynamic therapy for the treatment of depression. What does the evidence say about their relative effectiveness?",
    "Compare different approaches to inclusive education for students with disabilities. What does the research suggest about the effectiveness of full inclusion vs. specialized settings?",
    "Compare market-based and regulatory approaches to environmental protection. Under what conditions is each approach most effective?",
    "Compare the approaches to improvisation in jazz and classical Indian music (raga). What do they reveal about different conceptions of musical creativity?",
    "Compare the ethical frameworks of two different religious traditions on a specific issue (e.g., economic justice, environmental stewardship, or medical ethics).",
    "Compare the mechanisms of SN1 and SN2 nucleophilic substitution reactions. How do solvent, substrate, and nucleophile affect which pathway dominates?",
    "Compare the structure and function of the innate and adaptive immune systems. How do they work together to protect the body from infection?",
    "Compare the treatment of identity and belonging in two postcolonial novels from different national traditions. How do the authors negotiate between local and global concerns?",
    "Compare the treatment of national identity in the literature of two different language traditions. How do authors use language itself as a theme or tool?",
    "Compare the urban planning philosophies of Le Corbusier and Jane Jacobs. Whose vision has proven more successful in creating livable cities?",
    "Congressional polarization and legislative gridlock",
    "Critically evaluate the evidence for and against the dual-process theory of cognition (System 1 vs. System 2). How well does it explain real-world decision-making?",
    "Describe the development of group theory and its applications in physics, particularly in the study of symmetry and conservation laws.",
    "Discuss how GIS technology has transformed geographic research and decision-making across disciplines. Provide specific examples from public health, urban planning, or environmental science.",
    "Discuss how climate change is affecting global biodiversity, using specific examples of species and ecosystems. What conservation strategies are most promising?",
    "Discuss how modern dance pioneers (Martha Graham, Merce Cunningham, Alvin Ailey) each redefined the relationship between movement and meaning.",
    "Discuss how the discovery of graphene has influenced materials science research. What applications have been realized, and which remain theoretical?",
    "Discuss how the legacy of colonialism continues to shape political and economic structures in sub-Saharan Africa.",
    "Discuss how the transatlantic slave trade transformed the economies and societies of West Africa, the Americas, and Europe. What were its long-term legacies?",
    "Discuss the Sapir-Whorf hypothesis and the evidence for and against linguistic relativity. How does language influence thought?",
    "Discuss the advantages and limitations of additive manufacturing compared to traditional subtractive methods. What industries are most likely to benefit from widespread adoption?",
    "Discuss the bias-variance trade-off in statistical learning. How do regularization methods address overfitting, and when might a simpler model outperform a complex one?",
    "Discuss the causes and consequences of language endangerment worldwide. What strategies are most effective for language revitalization?",
    "Discuss the causes and consequences of political polarization in the United States. What institutional reforms could reduce partisan conflict?",
    "Discuss the causes and consequences of the Permian-Triassic mass extinction event. What lessons does it offer for understanding current biodiversity loss?",
    "Discuss the challenges and benefits of bilingual education. What does research in second language acquisition suggest about optimal approaches?",
    "Discuss the challenges and opportunities of integrating renewable energy sources into the existing power grid. How do smart grid technologies address these challenges?",
    "Discuss the challenges of regulating artificial intelligence under existing intellectual property and liability frameworks. What new legal frameworks might be needed?",
    "Discuss the concept of 'institutional critique' in contemporary art. How have artists questioned the role of museums, galleries, and the art market?",
    "Discuss the concept of the 'attention economy' and its effects on journalism and news consumption. How are business models reshaping the media landscape?",
    "Discuss the concept of the 'literary canon' and the ongoing debates about which works should be included. How have feminist and postcolonial scholars challenged traditional canon formation?",
    "Discuss the concept of theodicy across different religious traditions. How do Christianity, Judaism, and Buddhism each address the problem of suffering?",
    "Discuss the cultural and social significance of hip-hop music from its origins in the Bronx to its global influence. How has it served as a vehicle for social commentary?",
    "Discuss the digital divide in education. How does unequal access to technology affect educational outcomes, and what policies can address this gap?",
    "Discuss the economic arguments for and against a universal basic income. What does the evidence from pilot programs suggest about its effects on labor supply and welfare?",
    "Discuss the engineering challenges of designing buildings to withstand earthquakes. Compare the approaches used in Japan, Chile, and California.",
    "Discuss the engineering principles behind MRI, CT, and PET imaging. Compare their strengths and limitations for different diagnostic applications.",
    "Discuss the engineering trade-offs involved in designing reusable launch vehicles. How has SpaceX's approach changed the economics of space access?",
    "Discuss the ethical challenges of ethnographic research, including issues of informed consent, representation, and the researcher's positionality.",
    "Discuss the ethical responsibilities of documentary filmmakers. How do filmmakers balance the imperative to tell truth with the needs and rights of their subjects?",
    "Discuss the evolution of the American musical from its vaudeville origins to contemporary works like Hamilton. How have musical theater creators used the form to address social issues?",
    "Discuss the experimental evidence for the existence of dark matter. What are the leading theoretical candidates, and what challenges remain in detecting them?",
    "Discuss the feasibility of a fully circular economy. What technological, economic, and behavioral changes are needed to eliminate waste?",
    "Discuss the methods used to detect exoplanets and evaluate what we have learned about planetary system diversity from missions like Kepler and TESS.",
    "Discuss the origins, key arguments, and criticisms of Critical Race Theory. How has it influenced legal scholarship and public discourse?",
    "Discuss the philosophical implications of artificial intelligence for our understanding of consciousness, personhood, and moral status.",
    "Discuss the potential of gene-edited crops (CRISPR) for addressing food security challenges. What scientific, regulatory, and ethical issues must be considered?",
    "Discuss the principles and challenges of sustainable architecture. How can architects balance aesthetic ambition with environmental responsibility?",
    "Discuss the principles and practices of trauma-informed care. How can social service organizations implement a trauma-informed approach, and what evidence supports its effectiveness?",
    "Discuss the principles behind retrosynthetic analysis and apply them to propose a synthesis route for a complex organic molecule of your choice.",
    "Discuss the promise and risks of personalized medicine based on genomic data. What are the implications for health equity and access?",
    "Discuss the psychological mechanisms underlying implicit bias. What interventions have been shown to reduce implicit bias, and how effective are they?",
    "Discuss the relationship between gender identity and biological sex from the perspectives of biology, psychology, and social theory. What are the key areas of scientific consensus and ongoing debate?",
    "Discuss the role of chemical engineering in developing sustainable biofuel production processes. What are the main technical and economic barriers?",
    "Discuss the role of corporate social responsibility in modern business. Is CSR genuinely ethical, or is it primarily a marketing strategy? Support your argument with examples.",
    "Discuss the role of evidence-based practice in improving patient outcomes in nursing. What barriers exist to implementing research findings in clinical settings?",
    "Discuss the role of libraries in the digital age. How should libraries evolve to remain relevant as information access patterns change?",
    "Discuss the role of public architecture in the Roman Empire as a tool of political communication. Use specific examples from Rome and the provinces.",
    "Discuss the significance of Gödel's incompleteness theorems for the foundations of mathematics. What are their implications for the limits of formal systems?",
    "Discuss the sociological theories explaining the rise of social movements in the digital age. How has social media changed the dynamics of collective action?",
    "Discuss the tension between press freedom and national security. Under what circumstances, if any, should governments be permitted to restrict media reporting?",
    "Discuss the tension between state sovereignty and the responsibility to protect (R2P) in cases of mass atrocity. When, if ever, is humanitarian intervention justified?",
    "Discuss the trade-offs between relational and NoSQL database systems. Under what circumstances would you choose one over the other for a large-scale web application?",
    "Discuss the trade-offs inherent in universal health care systems. Compare the single-payer model with multi-payer systems in terms of cost, access, quality, and equity.",
    "Discuss whether large language models can be said to 'understand' language. What criteria should we use to evaluate machine understanding, and how do current models measure up?",
    "Evaluate Chomsky's theory of Universal Grammar in light of recent cross-linguistic and neuroscientific research. Is the concept of an innate language faculty still tenable?",
    "Evaluate Plato's theory of Forms. Is the concept of an abstract, perfect realm of ideas philosophically defensible in light of modern epistemology?",
    "Evaluate current approaches to water purification in developing countries. What low-cost, scalable solutions show the most promise?",
    "Evaluate different models of community organizing. How can social workers effectively mobilize communities to advocate for policy change?",
    "Evaluate the achievements and limitations of the #MeToo movement. How has it changed workplace culture and legal frameworks around sexual harassment?",
    "Evaluate the challenges of preserving and documenting dance as an ephemeral art form. How have notation systems and video technology changed this?",
    "Evaluate the concept of cultural relativism. What are its strengths as an analytical tool, and where does it encounter ethical limitations?",
    "Evaluate the concept of intersectionality and its contributions to understanding social inequality. Provide specific examples of how intersecting identities shape lived experiences.",
    "Evaluate the concept of reparations for slavery and its aftermath. What forms might reparations take, and what are the strongest arguments for and against them?",
    "Evaluate the concept of the 'auteur' in film criticism. Is it valid to attribute a film's artistic vision primarily to the director, given the collaborative nature of filmmaking?",
    "Evaluate the current state and future potential of brain-computer interfaces. What are the major technical and ethical challenges that must be addressed?",
    "Evaluate the effectiveness of international climate agreements (Kyoto, Paris) in reducing global greenhouse gas emissions. What improvements are needed?",
    "Evaluate the effectiveness of international criminal law in holding individuals accountable for genocide, war crimes, and crimes against humanity.",
    "Evaluate the effectiveness of the United Nations Security Council in maintaining international peace and security since the end of the Cold War.",
    "Evaluate the environmental impact of polymer production and disposal. What advances in biodegradable polymers and recycling technologies offer the most promise?",
    "Evaluate the ethical implications and scientific potential of CRISPR-Cas9 gene editing in human germline cells. What safeguards should be in place?",
    "Evaluate the ethical implications of algorithmic decision-making in information retrieval. How do search engine algorithms shape access to knowledge and influence public discourse?",
    "Evaluate the explanatory gap between neural activity and subjective experience. Can neuroscience ultimately explain consciousness, or are there principled limits?",
    "Evaluate the feasibility of quantum computing for solving problems that are intractable for classical computers. What are the main technical obstacles?",
    "Evaluate the future of local journalism in the United States. What business models and institutional structures can sustain quality local news coverage?",
    "Evaluate the global refugee crisis from both a human rights and a policy perspective. What reforms to the international refugee regime are most urgently needed?",
    "Evaluate the historiographical debate over the origins of the Cold War. Were the United States and Soviet Union equally responsible for the breakdown of the wartime alliance?",
    "Evaluate the human geographic factors driving international migration in the 21st century. How do push and pull factors interact across different scales?",
    "Evaluate the impact of digital music production tools on the democratization of music creation. How have DAWs, sampling, and streaming changed who can be a musician?",
    "Evaluate the impact of digital tools and AI on artistic creation. Do AI-generated images constitute 'art'? Defend your position with reference to philosophical and aesthetic arguments.",
    "Evaluate the impact of digital transformation on traditional retail business models. How should legacy retailers adapt their strategy to compete with e-commerce platforms?",
    "Evaluate the impact of the shift to online learning during and after the COVID-19 pandemic. What evidence-based practices for online instruction emerged, and what challenges remain?",
    "Evaluate the importance of cultural competence in health care delivery. How can health care professionals better serve diverse patient populations?",
    "Evaluate the influence of classical Greek political thought on modern democratic theory. Which ideas from Athenian democracy remain relevant, and which are problematic?",
    "Evaluate the legacy of Brutalist architecture. Why has this once-reviled style experienced a cultural reassessment, and what does this say about our changing relationship to buildings?",
    "Evaluate the replication crisis in psychology. What structural and methodological changes are needed to improve the reliability of psychological research?",
    "Evaluate the reproducibility crisis in data-driven research. What role do p-hacking, multiple testing, and publication bias play, and what methodological reforms can address them?",
    "Evaluate the role of CMOS technology scaling in enabling modern computing. What are the physical limits being approached, and what alternatives are being explored?",
    "Evaluate the role of behavioral economics in improving public policy. Provide specific examples of how nudges have been used effectively and discuss their limitations.",
    "Evaluate the role of composite materials in modern aircraft design. How do they compare to traditional aluminum alloys in terms of performance, cost, and recyclability?",
    "Evaluate the role of computational fluid dynamics in modern engineering design. What are its strengths and limitations compared to experimental methods?",
    "Evaluate the role of rhetoric in contemporary political campaigns. Analyze a specific speech or campaign using classical rhetorical frameworks.",
    "Evaluate the security implications of quantum computing for current cryptographic protocols. What post-quantum cryptographic schemes are most promising?",
    "Evaluate the sustainability of industrial animal agriculture. What alternative protein sources show the most promise for reducing environmental impact?",
    "Examine the role of ocean acidification in marine ecosystem degradation. What are the chemical mechanisms involved, and which organisms are most vulnerable?",
    "Explain how NMR spectroscopy works at the atomic level and discuss its applications in determining molecular structure.",
    "Explain how the cosmic microwave background radiation provides evidence for the Big Bang theory. What key features of the CMB have been confirmed by observations?",
    "Explain how the transformer architecture revolutionized natural language processing. Compare it with earlier approaches such as RNNs and LSTMs.",
    "Explain the concept of a topological space and discuss how topological invariants can be used to classify surfaces.",
    "Explain the endosymbiotic theory of mitochondrial and chloroplast origins. What molecular evidence supports this hypothesis?",
    "Explain the physical significance of Noether's theorem and how symmetries in nature lead to conservation laws. Provide at least two examples.",
    "FDA regulatory pathways for medical devices",
    "FPGA programming and hardware description languages",
    "Fourier transforms and spectral analysis",
    "German Expressionism and film noir aesthetics",
    "German Romanticism and national identity",
    "Greek tragedy and Aristotle's Poetics",
    "Gödel's incompleteness theorems",
    "Heidegger's being-in-the-world",
    "Homer's Iliad and the heroic ideal",
    "Islam and the concept of the ummah",
    "Lagrangian and Hamiltonian mechanics",
    "MOSFET operation and CMOS fabrication",
    "MRI physics and image reconstruction",
    "Martha Graham and the development of modern dance",
    "Maxwell's equations and electromagnetic waves",
    "Modernism, Postmodernism, and Deconstructivism",
    "Monte Carlo simulation in physics",
    "NP-completeness and computational complexity",
    "PID controllers and feedback stability",
    "Paris Agreement and nationally determined contributions",
    "Plato's Republic and the philosopher-king",
    "Rawls' theory of justice and its critics",
    "Renaissance perspective and humanism",
    "Schrödinger equation and quantum states",
    "Shakespeare's tragedies and early modern stagecraft",
    "South Asian classical dance forms (Bharatanatyam, Kathak)",
    "Stanislavski's system and method acting",
    "Sustainable Development Goals and their measurement",
    "TCP/IP protocol stack and routing algorithms",
    "Virgil's Aeneid and Roman imperial ideology",
    "abstract expressionism and the New York School",
    "acoustic phonetics and speech perception",
    "additive manufacturing and 3D printing technologies",
    "advertising psychology and persuasion techniques",
    "affordances and ecological psychology",
    "agile development and continuous integration",
    "air pollution control and emissions monitoring",
    "algorithmic content curation and filter bubbles",
    "analog and digital filter design",
    "ancient Greek theater and its ritual origins",
    "ancient civilization material culture and stratigraphy",
    "antibiotic resistance in bacterial populations",
    "asset pricing models and market efficiency",
    "atmospheric chemistry and ozone depletion",
    "attachment theory and childhood development",
    "auteur theory and directorial style",
    "autopilot design and flight stability",
    "bilingualism and cognitive advantages",
    "bioreactor design and fermentation technology",
    "black holes and gravitational waves",
    "bootstrap methods and resampling",
    "boundary layer theory and drag reduction",
    "brain-computer interfaces and neural decoding",
    "bureaucratic accountability and regulatory capture",
    "capital budgeting and discounted cash flow analysis",
    "carbon nanotubes and graphene applications",
    "carbon pricing mechanisms (cap-and-trade vs. carbon tax)",
    "cell signaling pathways and signal transduction",
    "ceramic sintering and fracture toughness",
    "chemical kinetics and reaction dynamics",
    "choreographic process and notation systems",
    "classical Chinese poetry and calligraphy",
    "classical ballet technique and Romantic era ballet",
    "climate modeling and greenhouse gas dynamics",
    "cognitive behavioral therapy for anxiety disorders",
    "collective action and protest mobilization",
    "college access, affordability, and completion",
    "community health assessment and outreach",
    "community needs assessment and asset mapping",
    "comparative advantage and trade agreements",
    "comparative religious ethics across traditions",
    "competitive advantage and Porter's five forces",
    "composite materials in aircraft structures",
    "compositional semantics and logical form",
    "computational fluid dynamics and turbulence modeling",
    "connectionist models and neural networks as cognitive models",
    "constructivist learning theory and inquiry-based instruction",
    "consumer behavior and market segmentation",
    "consumer choice theory and demand elasticity",
    "contemporary art and identity politics",
    "contract formation and breach remedies",
    "convolutional neural networks for object detection",
    "coordination compounds and crystal field theory",
    "coral reef ecology and ocean acidification",
    "criminal liability and mens rea",
    "crisis communication and reputation management",
    "cross-cultural perspectives on illness and healing",
    "crystal structure and defects in metals",
    "dance as cultural expression and identity",
    "dark matter and dark energy",
    "data journalism and computational reporting",
    "data visualization and exploratory analysis",
    "decolonization movements in the 20th century",
    "defamation law and shield laws for journalists",
    "deforestation and land use change",
    "democratic transitions and authoritarian resilience",
    "density functional theory calculations",
    "design thinking and user-centered design principles",
    "diffusion and molecular motors in biological cells",
    "digital audio workstations and electronic music production",
    "digital preservation and access",
    "disproportionate pollution burden on minority communities",
    "documentary ethics and modes of representation",
    "drug design and pharmacokinetics",
    "drug development pipeline and FDA approval",
    "dynamical systems and chaos theory",
    "educational attainment gaps and school segregation",
    "electrochemistry and redox reactions",
    "electronic health records and clinical decision support",
    "employee motivation and organizational culture",
    "environmental regulation and climate litigation",
    "enzyme catalysis and metabolic pathways",
    "epigenetics and gene regulation",
    "ethnographic methods and participant observation",
    "evidence-based interventions for substance use disorders",
    "evidence-based medicine and clinical trial design",
    "evidence-based nursing practice",
    "existence and uniqueness theorems for ODEs",
    "exoplanet detection methods (transit, radial velocity)",
    "feminist literary criticism and the canon",
    "feudalism and the Crusades",
    "finite element methods for PDEs",
    "fiscal policy and deficit spending",
    "food preservation technologies and shelf-life extension",
    "forced displacement and asylum policy",
    "fossil record and mass extinction events",
    "foster care system and adoption policy",
    "free will and moral responsibility",
    "fundamental group and covering spaces",
    "galaxy formation and large-scale structure",
    "gender wage gap and occupational segregation",
    "general relativity and curved spacetime",
    "generative grammar and syntactic trees",
    "genome assembly and sequence alignment algorithms",
    "gentrification and neighborhood change",
    "geomorphology and landscape evolution",
    "global food supply chains and food security",
    "graph coloring and Ramsey theory",
    "group theory and ring homomorphisms",
    "harmonic analysis and voice leading",
    "health care system design and universal coverage",
    "heat exchanger design and thermal efficiency",
    "hip-hop as cultural and artistic movement",
    "human evolution and hominin fossil record",
    "implicit bias and stereotype threat",
    "inclusive education and accommodations for learning disabilities",
    "infectious disease epidemiology and outbreak investigation",
    "informed consent and end-of-life decision-making",
    "innate vs. adaptive immune responses",
    "instrumental variables and causal inference",
    "intellectual freedom and censorship",
    "interactive art and virtual reality installations",
    "international humanitarian law and armed conflict",
    "jazz improvisation and harmonic theory",
    "jet engine thermodynamic cycles",
    "judicial review and constitutional interpretation",
    "kinship systems and social organization",
    "language disorders and speech therapy approaches",
    "language endangerment and documentation",
    "language families and sound change",
    "language variation and dialect geography",
    "large language models and prompt engineering",
    "leadership theories and organizational culture",
    "lean startup methodology and minimum viable products",
    "learning management systems and online pedagogy",
    "linear algebra and spectral theory",
    "literary movements in French modernism",
    "livestock genetics and selective breeding",
    "magical realism in Latin American fiction",
    "market structure and antitrust regulation",
    "mass incarceration and recidivism",
    "mass transfer and separation processes",
    "mate selection and parental investment theory",
    "meaning, reference, and truth conditions",
    "measure theory and Lebesgue integration",
    "media framing and agenda-setting theory",
    "metadata schemas and ontology design",
    "microfinance and poverty alleviation strategies",
    "migration patterns and transnational communities",
    "mixed-use urban development and transit-oriented design",
    "modal logic and possible worlds",
    "modern Japanese literature and postwar identity",
    "monetary policy and inflation targeting",
    "motion planning and simultaneous localization and mapping",
    "motivation, self-regulation, and academic achievement",
    "multilateral institutions and global cooperation",
    "music and protest movements globally",
    "narrative structure and the three-act screenplay",
    "narrative structure in modernist fiction",
    "natural law theory vs. legal positivism",
    "natural selection and adaptive radiation",
    "net-zero energy buildings and passive house standards",
    "neural correlates of consciousness and the binding problem",
    "neural correlates of decision-making",
    "neural plasticity and synaptic transmission",
    "nonverbal communication and cultural differences",
    "nuclear deterrence and arms control",
    "nutritional biochemistry and dietary interventions",
    "objectivity and bias in news reporting",
    "ocean circulation patterns and thermohaline conveyor",
    "opera and its political context",
    "optimal taxation and public goods provision",
    "organizational knowledge sharing and tacit knowledge",
    "parametric design and computational architecture",
    "patent, copyright, and trademark protections",
    "performance practice in Baroque music",
    "performativity and the social construction of gender",
    "photosynthesis and carbon fixation pathways",
    "physical rehabilitation and occupational therapy",
    "pipelining and cache coherence protocols",
    "plate tectonics and continental drift",
    "polymer chain architecture and mechanical properties",
    "polymer processing and rheology",
    "polymer synthesis and characterization",
    "population dynamics and predator-prey models",
    "post-conflict reconstruction and transitional justice",
    "postcolonial identity and language in African literature",
    "precision agriculture and drone-based crop monitoring",
    "press freedom and media regulation",
    "prime distribution and the Riemann hypothesis",
    "prior specification and posterior inference",
    "process safety and hazard analysis",
    "process scheduling and memory management",
    "product lifecycle assessment and cradle-to-cradle design",
    "project scheduling and cost estimation",
    "prospect theory and loss aversion",
    "prosthetic limb design and gait analysis",
    "public-key cryptography and zero-knowledge proofs",
    "quantum computing and quantum gates",
    "query optimization and distributed databases",
    "random forests and gradient boosting methods",
    "ray tracing and physically-based rendering",
    "reaction mechanisms and stereochemistry",
    "reactor design and catalytic process optimization",
    "real-time operating systems for embedded platforms",
    "remote sensing and GIS applications",
    "reproductive rights and bodily autonomy",
    "rhetorical analysis of political discourse",
    "robotic actuators and sensor integration",
    "satellite orbit determination and maneuvers",
    "scaffold materials for tissue regeneration",
    "scenic design and stagecraft technology",
    "school choice and voucher programs",
    "school funding formulas and educational equity",
    "scientific realism vs. anti-realism",
    "second language acquisition theories",
    "secularization theory and religious pluralism",
    "seismic design and earthquake-resistant structures",
    "seismology and earthquake prediction",
    "semiconductor doping and band engineering",
    "sentence processing and garden-path effects",
    "skepticism and the problem of knowledge",
    "smart grid technology and renewable energy integration",
    "social determinants of health disparities",
    "social mobility and intergenerational wealth transfer",
    "soil mechanics and foundation design",
    "soil microbiome and nutrient cycling",
    "soil science and land degradation",
    "solar and wind energy grid integration",
    "sovereignty and self-determination of Indigenous peoples",
    "spatial analysis and remote sensing",
    "spectroscopic methods (NMR, mass spec, IR)",
    "stakeholder theory and ESG reporting",
    "statistical ensembles and partition functions",
    "stellar evolution and the Hertzsprung-Russell diagram",
    "stem cell differentiation and tissue engineering",
    "stress analysis and finite element methods",
    "stress, coping, and health outcomes",
    "structural equation modeling in behavioral research",
    "structural racism and institutional discrimination",
    "structural racism and systemic inequality",
    "structural systems and material innovation in tall buildings",
    "superconductivity and Bose-Einstein condensation",
    "supply chain optimization and logistics",
    "textual criticism and biblical hermeneutics",
    "the American Civil War and Reconstruction",
    "the American novel and national identity",
    "the Black Atlantic and cultural exchange",
    "the French Revolution and the rise of nationalism",
    "the Harlem Renaissance and Black cultural production",
    "the Holocaust and its historical interpretations",
    "the Meiji Restoration and Japanese modernization",
    "the Ottoman Empire and its legacy",
    "the Protestant Reformation and its political consequences",
    "the Scientific Revolution and its intellectual roots",
    "the Standard Model of particle physics",
    "the cosmic microwave background radiation",
    "the craft of fiction: voice, point of view, and structure",
    "the definition of art and aesthetic experience",
    "the evolution of the American musical",
    "the expanding universe and Hubble's law",
    "the gender pay gap and occupational segregation",
    "the history and techniques of animation",
    "the mind-body problem and consciousness",
    "the model minority myth and Asian American experiences",
    "the political economy of trade liberalization",
    "the problem of evil and theodicy",
    "the reception of classical mythology in modern art",
    "the relationship between photography and truth",
    "the replication crisis in psychology",
    "the role of museums and art institutions",
    "the sonnet form and its evolution",
    "theories of justice and distributive fairness",
    "thermodynamics of chemical equilibria",
    "toxic masculinity and changing norms of manhood",
    "traffic flow modeling and intelligent transportation systems",
    "transatlantic slave trade and its demographic impact",
    "transformer architecture and attention mechanisms",
    "trauma-informed care principles",
    "tropical diseases and neglected health conditions",
    "type systems and compiler optimization passes",
    "universal health care models and cost containment",
    "universal human rights vs. cultural particularism",
    "utilitarianism vs. deontological ethics",
    "vibration isolation and modal analysis",
    "visual perception and change blindness",
    "voter behavior and electoral systems",
    "wage determination and labor market discrimination",
    "wastewater treatment and water purification",
    "water resource management and aquifer depletion",
    "wave-particle duality and the uncertainty principle",
    "waves of feminism and their evolving priorities",
    "welfare policy and poverty reduction strategies",
    "wildlife corridors and habitat fragmentation",
    "working memory models and cognitive load",
    "zoning policy and urban sprawl",
]
